# Generated by Django 3.2.18 on 2023-03-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Тэг')),
                ('color', models.CharField(max_length=50, unique=True, verbose_name='Цвет')),
                ('slug', models.SlugField(unique=True, verbose_name='Уникальный slug')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ('id',),
            },
        ),
    ]
