# Generated by Django 3.2.18 on 2023-03-23 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recopes', '0003_auto_20230316_2156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoopCart',
            new_name='ShopCart',
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_follow',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_subscribed'),
        ),
    ]
