# Generated by Django 3.2.18 on 2023-03-23 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recopes', '0004_auto_20230323_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='recopes.recipe', verbose_name='Рецепт'),
        ),
    ]
