# Generated by Django 3.2.18 on 2023-03-30 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recopes', '0006_auto_20230330_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-created_date',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
